# Generated by Django 4.2.10 on 2025-10-07 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeBasic',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('servings', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('ingredients', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeString',
            fields=[
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cook', serialize=False, to='recipe.recipebasic')),
                ('raw_text', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
